"""
 Collects the last <SAMPLE_SIZE> random values generated by the NIST Randomness Beacon (https://beacon.nist.gov/home), and saves them to a csv.
 Date: Oct 22,2020
"""

import requests
import time

SAMPLE_SIZE = 8000

init = requests.get("https://beacon.nist.gov/beacon/2.0/pulse/last").json()
nextUri = init["pulse"]["listValues"][0]["uri"]

for i in range(8000):
	success = False
	while not success: #keep trying until the request succeeds, guaranteeing <SAMPLE_SIZE> values
		request = requests.get(nextUri)
		
		if request.status_code == 200:
			success = True

			response = request.json()
			
			nextUri = response["pulse"]["listValues"][0]["uri"]

			f = open('beacon_values.csv', 'a')

			f.write(str(response["pulse"]["localRandomValue"]) + ',')

			f.close()

